// Code generated by hertz generator.

package chat

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createchatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsessionmsgMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsessionlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
