// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SessionID  int64     `gorm:"column:session_id;not null" json:"session_id"`
	UserID     int64     `gorm:"column:user_id;not null" json:"user_id"`
	Data       string    `gorm:"column:data;not null" json:"data"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	AudioKey   string    `gorm:"column:audio_key;not null;comment:消息的音频key" json:"audio_key"` // 消息的音频key
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
